RGBLIGHT_ENABLE    		= no
RGBLIGHT_ANIMATIONS 	= no
RGBLIGHT_SPLIT_ENABLE 	= no

RGB_MATRIX_ENABLE  		= WS2812
RGB_MATRIX_KEYPRESSES 	= no

NKRO_ENABLE        		= yes
OLED_DRIVER_ENABLE 		= yes
TAP_DANCE_ENABLE 		= no
EXTRAKEY_ENABLE 		= yes
SPLIT_TRANSPORT 		= mirror

BOOTMAGIC_ENABLE        = no
MOUSEKEY_ENABLE         = no
CONSOLE_ENABLE          = no
COMMAND_ENABLE          = no
RAW_ENABLE 				= yes

BOOTLOADER = qmk-dfu