RGB_MATRIX_ENABLE  		= WS2812

NKRO_ENABLE        		= yes
OLED_DRIVER_ENABLE 		= yes
TAP_DANCE_ENABLE 		= no
EXTRAKEY_ENABLE 		= yes

BOOTMAGIC_ENABLE        = no
MOUSEKEY_ENABLE         = no
CONSOLE_ENABLE          = yes
COMMAND_ENABLE          = no
RAW_ENABLE 				= yes

BOOTLOADER = qmk-dfu
